### ISSUE TITLE
Batch Download

### ISSUE THREAD

**Issue by vstenby** [YoonAddicting/DTU-Video-Downloader#1]
Hello!

I am using your DTU-Video-Downloader for a hobby project, and I was wondering if batch download is going to be a feature.

It takes a bit of time to set the downloader to download all of the seperate videos, and I would just like to post an URL to a course (e.g. https://video.dtu.dk/category/Courses%3E01+Department+of+Applied+Mathematics+and+Computer+Science%3E01005+Matematik+1%3EE19_F20%3ESkema+B/241155) and then have the DTU-Video-Downloader download all of the available videos.

Is this something you could consider implementing?

Best wishes,
vstenby

**Comment by jonasbp2011** [comment]
I've merged your pull request, therefore I consider this solved.
